---@class (exact) __inner.meth
---@field vec2_metatable metatable
---@field ivec2_metatable metatable
---@field vec3_metatable metatable
---@field ivec3_metatable metatable
---@field vec4_metatable metatable
---@field ivec4_metatable metatable
---@field mat2_metatable metatable
---@field mat3_metatable metatable
---@field mat4_metatable metatable

---@meta
---@class (exact) __inner
---@field meth __inner.meth
